name: InventoryManager
version: 1.0
main: com.smp.inventory.InventoryManagerPlugin
api-version: 1.19
author: Jangamar
description: Manages separate inventories for different world groups

# This plugin keeps inventories connected for Lobbyj/world group
# while keeping other worlds (LobbyPractice, Arenas) completely separate
