name: DiscordBridge
version: 1.0.0
main: com.smpstats.discordbridge.DiscordBridge
api-version: 1.20
depend: [DiscordSRV]
description: Bridges DiscordSRV verification codes to website
author: SMPStats
commands: {}
