CREATE TABLE IF NOT EXISTS high_tiers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rank INT NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_username (username)
);
